"""
tests/test_regression.py
------------------------
Regression suite: ensures that future changes to the sanitizer do NOT alter
the fingerprints of 50 known, diverse log samples drawn from logs.json.

Fixture file: tests/fixtures/regression_samples.json
Generated by: python scripts/generate_regression_samples.py

If you intentionally change sanitization rules (and the fingerprint changes
are expected), regenerate the fixture file and commit the updated golden file.
"""
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.analyzer.sanitizer import sanitize  # noqa: E402

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "regression_samples.json"


# ─────────────────────────────────────────────────────────────────────────────
# Fixture loading
# ─────────────────────────────────────────────────────────────────────────────

def load_samples() -> list[dict]:
    if not FIXTURE_PATH.exists():
        pytest.fail(
            f"Regression fixture not found: {FIXTURE_PATH}\n"
            "Run: python scripts/generate_regression_samples.py"
        )
    with open(FIXTURE_PATH, encoding="utf-8") as fh:
        return json.load(fh)


SAMPLES = load_samples()


# ─────────────────────────────────────────────────────────────────────────────
# Parametrized regression tests
# ─────────────────────────────────────────────────────────────────────────────

@pytest.mark.parametrize(
    "sample",
    SAMPLES,
    ids=[f"{s['category']}-{i:02d}" for i, s in enumerate(SAMPLES)],
)
def test_fingerprint_stability(sample: dict) -> None:
    """
    The sanitizer must produce exactly the same fingerprint for each known
    log sample. A mismatch signals that a rule change has altered the
    fingerprinting behaviour — intended changes require a fixture regeneration.
    """
    message: str = sample["message"]
    expected: str = sample["expected_fingerprint"]
    category: str = sample["category"]

    result = sanitize(message)
    actual: str = result.fingerprint

    assert actual == expected, (
        f"\nFingerprint mismatch for category='{category}'\n"
        f"  expected : {expected}\n"
        f"  actual   : {actual}\n"
        f"  sanitized: {result.sanitized[:200]}\n"
        f"  rules    : {result.rules_applied}\n"
        f"  message  : {message[:200]}"
    )


# ─────────────────────────────────────────────────────────────────────────────
# Category-level coverage assertions
# ─────────────────────────────────────────────────────────────────────────────

class TestCategoryCoverage:
    """Ensure the fixture has at least 2 samples per critical category."""

    REQUIRED_CATEGORIES = [
        "vpc_flow",
        "unauthorized",
        "mimecast",
        "api_error",
        "timestamp_parse",
        "dns",
        "ms_auth",
    ]

    @pytest.mark.parametrize("category", REQUIRED_CATEGORIES)
    def test_category_represented(self, category: str) -> None:
        count = sum(1 for s in SAMPLES if s["category"] == category)
        assert count >= 2, (
            f"Category '{category}' has only {count} sample(s) in the fixture. "
            "Regenerate with python scripts/generate_regression_samples.py"
        )

    def test_total_sample_count(self) -> None:
        assert len(SAMPLES) == 50, (
            f"Expected 50 regression samples, got {len(SAMPLES)}. "
            "Regenerate with python scripts/generate_regression_samples.py"
        )


# ─────────────────────────────────────────────────────────────────────────────
# VPC Flow deduplication smoke test
# ─────────────────────────────────────────────────────────────────────────────

class TestVpcFlowDeduplication:
    """All VPC flow samples in the fixture must share a single fingerprint."""

    def test_all_accept_flows_same_fingerprint(self) -> None:
        vpc_samples = [s for s in SAMPLES if s["category"] == "vpc_flow"]
        if len(vpc_samples) < 2:
            pytest.skip("Not enough VPC flow samples to test deduplication")

        fingerprints = {s["expected_fingerprint"] for s in vpc_samples}
        # All VPC flow logs should collapse to a very small number of patterns
        # (typically 1 for ACCEPT, 1 for REJECT).
        assert len(fingerprints) <= 3, (
            f"VPC flow logs are over-fragmented: {len(fingerprints)} unique fingerprints "
            f"from {len(vpc_samples)} samples. Review VPC_FLOW_RAWMSG and JSON sanitization rules."
        )


# ─────────────────────────────────────────────────────────────────────────────
# Unauthorized exception deduplication smoke test
# ─────────────────────────────────────────────────────────────────────────────

class TestUnauthorizedDeduplication:
    """All Unauthorized exception samples must produce the same fingerprint."""

    def test_all_unauthorized_same_fingerprint(self) -> None:
        unauth_samples = [s for s in SAMPLES if s["category"] == "unauthorized"]
        if len(unauth_samples) < 2:
            pytest.skip("Not enough Unauthorized samples")

        fingerprints = {s["expected_fingerprint"] for s in unauth_samples}
        assert len(fingerprints) == 1, (
            f"Unauthorized exceptions produced {len(fingerprints)} fingerprints "
            f"instead of 1. Review LINUX_PATH rule."
        )
